#!/bin/bash
#
# Perform necessary cloudkeeper removal steps
# after package is uninstalled.
#

PROGNAME=$(basename $0)
INSTALLER_DIR=`dirname $0`

SYSD_DIR="/etc/systemd/system"
BIN_DIR="/usr/bin"

DEST_DIR="/opt/cloudkeeper"
CONFIG_DIR="/etc/cloudkeeper"
LOG_DIR="/var/log/cloudkeeper"
SPOOL_DIR="/var/spool/cloudkeeper"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

function remdir
{
  if [ -d "$1" ]; then
    rm -rf "$1" || error_exit "Could not unlink $1"
  fi
}

if [ "X$1" = "Xpurge" ] || [ "X$1" = "X0" ]; then
  # clean up systemd integration
  for SD_FILE in ${SYSD_DIR}/cloudkeeper.* ; do
    rm "$SD_FILE" || error_exit "Could not unlink $SD_FILE"
  done

  # clean up bin links
  if [ -L "$BIN_DIR/cloudkeeper" ]; then
    rm "$BIN_DIR/cloudkeeper"
  fi

  # clean up runtime directories
  remdir "$DEST_DIR"
  remdir "$CONFIG_DIR"
  remdir "$LOG_DIR"
  remdir "$SPOOL_DIR"
fi

echo "cloudkeeper has been uninstalled!"

exit 0
