#!/bin/bash
#
# Perform necessary cloudkeeper removal steps
# after package is uninstalled.
#

PROGNAME=$(basename $0)
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/cloudkeeper
CONFIG_DIR=/etc/cloudkeeper
BIN_DIR=/usr/bin
CRON_DIR=/etc/cron.d
INIT_DIR=/etc/init.d

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if [ "X$1" = "Xpurge" ] || [ "X$1" = "X0" ]; then
  # clean up cron integration
  if [ -f "$CRON_DIR/cloudkeeper" ]; then
    rm $CRON_DIR/cloudkeeper
  fi

  # clean up init scripts
  if [ -f "$INIT_DIR/cloudkeeper-cron" ]; then
    rm $INIT_DIR/cloudkeeper-cron
  fi

  # clean up links
  if [ -L "$BIN_DIR/cloudkeeper" ]; then
    rm $BIN_DIR/cloudkeeper
  fi
fi

echo "cloudkeeper has been uninstalled!"

exit 0
