#!/bin/bash
#
# Perform necessary cloudkeeper setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# stop cron service
service cloudkeeper-cron stop

exit 0
